services:
  db:
    image: mysql:8.0.36
    container_name: yozora-db
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: yozora
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
